# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_SOFG_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WtyczkaDialogBase(object):
    def setupUi(self, WtyczkaDialogBase):
        WtyczkaDialogBase.setObjectName("WtyczkaDialogBase")
        WtyczkaDialogBase.resize(558, 542)
        self.button_box = QtWidgets.QDialogButtonBox(WtyczkaDialogBase)
        self.button_box.setGeometry(QtCore.QRect(180, 480, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.label = QtWidgets.QLabel(WtyczkaDialogBase)
        self.label.setGeometry(QtCore.QRect(60, 50, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(WtyczkaDialogBase)
        self.label_2.setGeometry(QtCore.QRect(50, 180, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.wynik_dh = QtWidgets.QLabel(WtyczkaDialogBase)
        self.wynik_dh.setGeometry(QtCore.QRect(340, 180, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.wynik_dh.setFont(font)
        self.wynik_dh.setText("")
        self.wynik_dh.setObjectName("wynik_dh")
        self.label_4 = QtWidgets.QLabel(WtyczkaDialogBase)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.wynik_pole = QtWidgets.QLabel(WtyczkaDialogBase)
        self.wynik_pole.setGeometry(QtCore.QRect(340, 300, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.wynik_pole.setFont(font)
        self.wynik_pole.setText("")
        self.wynik_pole.setObjectName("wynik_pole")
        self.warstwa = QgsMapLayerComboBox(WtyczkaDialogBase)
        self.warstwa.setGeometry(QtCore.QRect(250, 50, 241, 27))
        self.warstwa.setObjectName("warstwa")
        self.oblicz_dh = QtWidgets.QPushButton(WtyczkaDialogBase)
        self.oblicz_dh.setGeometry(QtCore.QRect(152, 120, 261, 28))
        self.oblicz_dh.setObjectName("oblicz_dh")
        self.oblicz_pole = QtWidgets.QPushButton(WtyczkaDialogBase)
        self.oblicz_pole.setGeometry(QtCore.QRect(150, 240, 251, 28))
        self.oblicz_pole.setObjectName("oblicz_pole")
        self.error = QtWidgets.QLabel(WtyczkaDialogBase)
        self.error.setGeometry(QtCore.QRect(80, 390, 391, 41))
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(WtyczkaDialogBase)
        self.button_box.accepted.connect(WtyczkaDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(WtyczkaDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WtyczkaDialogBase)

    def retranslateUi(self, WtyczkaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        WtyczkaDialogBase.setWindowTitle(_translate("WtyczkaDialogBase", "wtyczka_SOFG"))
        self.label.setText(_translate("WtyczkaDialogBase", "Wybierz warstwę"))
        self.label_2.setText(_translate("WtyczkaDialogBase", "Obliczone przewyższenie"))
        self.label_4.setText(_translate("WtyczkaDialogBase", "Obliczone pole powierzchni "))
        self.oblicz_dh.setText(_translate("WtyczkaDialogBase", "OBLICZ dh"))
        self.oblicz_pole.setText(_translate("WtyczkaDialogBase", "OBLICZ POLE "))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WtyczkaDialogBase = QtWidgets.QDialog()
    ui = Ui_WtyczkaDialogBase()
    ui.setupUi(WtyczkaDialogBase)
    WtyczkaDialogBase.show()
    sys.exit(app.exec_())
